
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  redpanda:
    image: redpandadata/redpanda:latest

    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp 1
      - --memory 1G
      - --reserve-memory 0M
    ports:
      - "9092:9092"
  app:
    build: .
    depends_on:
      - db
      - redis
      - redpanda
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/postgres
      REDIS_URL: redis://redis:6379/0
    ports:
      - "8000:8000"
volumes:
  pgdata:
